<?php

/**
 * User: sujianhui
 * Date: 2017-10-25
 * Time: 9:30
 */
namespace classes\decorator;

use classes\decorator\Decorator;

class DecoratorA extends Decorator
{
    public function operation()
    {
        parent::operation(); // TODO: Change the autogenerated stub
        $this->selfBehaviors();
    }

    public function selfBehaviors(){
        echo 'wear '.__CLASS__.'<br/>';
    }
}